import type { AchievementDefinition } from "../../types";

export const ACHIEVEMENT_DEFINITIONS: readonly Readonly<AchievementDefinition>[] = [
  // ── Combat ──────────────────────────────────────────────────────────
  {
    id: "first_blood",
    name: "First Blood",
    description: "Destroy your first enemy.",
    icon: "crosshair",
    category: "combat",
    condition: { type: "stat_threshold", stat: "total_kills", threshold: 1 },
  },
  {
    id: "century_kills",
    name: "Century",
    description: "Destroy 100 enemies.",
    icon: "skull",
    category: "combat",
    condition: { type: "stat_threshold", stat: "total_kills", threshold: 100 },
  },
  {
    id: "genocide",
    name: "Genocide",
    description: "Destroy 1,000 enemies.",
    icon: "skull_fire",
    category: "combat",
    condition: { type: "stat_threshold", stat: "total_kills", threshold: 1000 },
  },
  {
    id: "boss_slayer",
    name: "Boss Slayer",
    description: "Defeat a boss.",
    icon: "crown",
    category: "combat",
    condition: { type: "stat_threshold", stat: "bosses_killed", threshold: 1 },
  },
  {
    id: "ramming_speed",
    name: "Ramming Speed",
    description: "Destroy an enemy by ramming into it.",
    icon: "explosion",
    category: "combat",
    condition: { type: "single_event", eventType: "ram_kill" },
    hidden: true,
  },

  // ── Survival ────────────────────────────────────────────────────────
  {
    id: "untouchable",
    name: "Untouchable",
    description: "Complete a level without taking any damage.",
    icon: "shield",
    category: "survival",
    condition: { type: "single_event", eventType: "no_damage_level" },
  },
  {
    id: "close_call",
    name: "Close Call",
    description: "Survive with armor below 10%.",
    icon: "heart_crack",
    category: "survival",
    condition: { type: "single_event", eventType: "armor_below_10pct" },
  },
  {
    id: "nine_lives",
    name: "Nine Lives",
    description: "Survive 9 deaths.",
    icon: "cat",
    category: "survival",
    condition: { type: "stat_threshold", stat: "deaths_survived", threshold: 9 },
  },
  {
    id: "dodge_master",
    name: "Dodge Master",
    description: "Perform 50 successful dodges.",
    icon: "wind",
    category: "survival",
    condition: { type: "stat_threshold", stat: "total_dodges", threshold: 50 },
  },

  // ── Progression ─────────────────────────────────────────────────────
  {
    id: "first_sortie",
    name: "First Sortie",
    description: "Complete your first level.",
    icon: "flag",
    category: "progression",
    condition: { type: "single_event", eventType: "level_complete" },
  },
  {
    id: "halfway_there",
    name: "Halfway There",
    description: "Complete 5 levels.",
    icon: "map",
    category: "progression",
    condition: { type: "stat_threshold", stat: "levels_completed", threshold: 5 },
  },
  {
    id: "victory",
    name: "Victory",
    description: "Complete all 10 levels.",
    icon: "trophy",
    category: "progression",
    condition: { type: "stat_threshold", stat: "levels_completed", threshold: 10 },
  },
  {
    id: "high_scorer",
    name: "High Scorer",
    description: "Reach a total score of 100,000.",
    icon: "star",
    category: "progression",
    condition: { type: "stat_threshold", stat: "total_score", threshold: 100000 },
  },
  {
    id: "millionaire",
    name: "Millionaire",
    description: "Reach a total score of 1,000,000.",
    icon: "gem",
    category: "progression",
    condition: { type: "stat_threshold", stat: "total_score", threshold: 1000000 },
  },

  // ── Collection ──────────────────────────────────────────────────────
  {
    id: "power_hungry",
    name: "Power Hungry",
    description: "Collect 50 power-ups.",
    icon: "zap",
    category: "collection",
    condition: { type: "stat_threshold", stat: "power_ups_collected", threshold: 50 },
  },
  {
    id: "fully_loaded",
    name: "Fully Loaded",
    description: "Own all 7 weapon types at once.",
    icon: "arsenal",
    category: "collection",
    condition: { type: "stat_threshold", stat: "unique_weapons_owned", threshold: 7 },
  },
  {
    id: "max_tier",
    name: "Max Tier",
    description: "Upgrade any weapon to tier 10.",
    icon: "chevrons_up",
    category: "collection",
    condition: { type: "single_event", eventType: "weapon_tier_max" },
  },
  {
    id: "bomb_hoarder",
    name: "Bomb Hoarder",
    description: "Hold the maximum of 5 mega-bombs.",
    icon: "bomb",
    category: "collection",
    condition: { type: "single_event", eventType: "bombs_at_max" },
  },

  // ── Mastery ─────────────────────────────────────────────────────────
  {
    id: "emp_expert",
    name: "EMP Expert",
    description: "Fire 25 EMP bursts.",
    icon: "bolt",
    category: "mastery",
    condition: { type: "stat_threshold", stat: "total_emps", threshold: 25 },
  },
  {
    id: "deflector_pro",
    name: "Deflector Pro",
    description: "Deflect 10 projectiles with the deflector shield.",
    icon: "rotate",
    category: "mastery",
    condition: { type: "stat_threshold", stat: "total_reflects", threshold: 10 },
  },
  {
    id: "speedrunner",
    name: "Speedrunner",
    description: "Complete a level in under 2 minutes.",
    icon: "timer",
    category: "mastery",
    condition: { type: "single_event", eventType: "level_under_2min" },
    hidden: true,
  },
] as const;
