import { RaptorLevelConfig, WeaponType } from "./types";

export const LEVELS: RaptorLevelConfig[] = [
  {
    level: 1,
    name: "Coastal Patrol",
    waves: [
      { enemyVariant: "scout", count: 5, spawnDelay: 0.8, waveDelay: 1, formation: "line", speed: 150 },
      { enemyVariant: "scout", count: 6, spawnDelay: 0.7, waveDelay: 8, formation: "v", speed: 160 },
      { enemyVariant: "scout", count: 5, spawnDelay: 0.6, waveDelay: 15, formation: "random", speed: 170 },
      { enemyVariant: "drone", count: 7, spawnDelay: 0.4, waveDelay: 18, formation: "random", speed: 160 },
      { enemyVariant: "scout", count: 7, spawnDelay: 0.5, waveDelay: 22, formation: "sweep", speed: 180 },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "standard", hitPoints: 25, speed: 50, fireRate: 0.8, scoreValue: 200, appearsAfterWave: 3, weaponType: "standard" },
    autoFireRate: 5,
    powerUpDropChance: 0.10,
    skyGradient: ["#87CEEB", "#E0F0FF"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.0,
    terrain: {
      theme: "coastal",
      horizonAssets: ["horizon_coastal"],
      groundColor: "#4d8c3f",
      groundTexture: "ground_grass",
      structurePool: ["struct_beach_hut", "struct_lighthouse", "struct_palm_tree"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_debris"],
      propDensity: 3,
      hasWater: true,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(200, 230, 255, 0.6)",
        count: 30,
        speedRange: [15, 40],
        sizeRange: [1, 2.5],
        drift: 20,
      },
    },
    act: 1,
    story: {
      briefing: "Vektran scouts have been spotted along the southern coastline — the first confirmed enemy presence on the continent. Admiral Rennick is deploying you on a patrol sweep to gauge enemy strength and eliminate their forward scouts before they can establish a beachhead. This is our first real look at what we're up against.",
      completionText: "Coastal sector secured. But the engagement data paints a grim picture — these scouts were probing our defenses, feeding intel back to a larger force massing in the desert interior. Command is rerouting you inland immediately. No time to rest.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: Rennick here. Radar shows multiple contacts along the coast. Engage at will, Archer.", speaker: "hq" },
        { triggerTime: 9, text: "Wingman: Second wave coming in from the north — they're trying to flank us.", speaker: "wingman" },
        { triggerTime: 16, text: "Sensor: Energy signatures spiking ahead. Something bigger is out there.", speaker: "sensor" },
        { triggerTime: 24, text: "HQ: We're reading a command-class vessel on approach. Take it down before it calls in reinforcements.", speaker: "hq" },
      ],
    },
  },
  {
    level: 2,
    name: "Desert Strike",
    waves: [
      { enemyVariant: "scout", count: 5, spawnDelay: 0.7, waveDelay: 1, formation: "line", speed: 170 },
      { enemyVariant: "fighter", count: 3, spawnDelay: 1.0, waveDelay: 7, formation: "v", speed: 120 },
      { enemyVariant: "dart", count: 6, spawnDelay: 0.5, waveDelay: 11, formation: "sweep", speed: 280 },
      { enemyVariant: "scout", count: 6, spawnDelay: 0.6, waveDelay: 14, formation: "sweep", speed: 180 },
      { enemyVariant: "fighter", count: 4, spawnDelay: 0.9, waveDelay: 20, formation: "random", speed: 130, weaponType: "spread" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.4, waveDelay: 25, formation: "line", speed: 300 },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.5, waveDelay: 28, formation: "line", speed: 190 },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "gunship_commander", hitPoints: 35, speed: 60, fireRate: 1.0, scoreValue: 300, appearsAfterWave: 4, weaponType: "spread" },
    autoFireRate: 5,
    powerUpDropChance: 0.12,
    skyGradient: ["#F4A460", "#87CEEB"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.0,
    weaponDrops: ["rocket"] as WeaponType[],
    terrain: {
      theme: "desert",
      horizonAssets: ["horizon_desert"],
      groundColor: "#c8a060",
      groundTexture: "ground_sand",
      structurePool: ["struct_oil_rig", "struct_cactus", "struct_bunker"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_crater", "prop_tire_tracks"],
      propDensity: 4,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(210, 180, 120, 0.5)",
        count: 50,
        speedRange: [20, 60],
        sizeRange: [0.5, 2],
        drift: 40,
      },
    },
    act: 1,
    story: {
      briefing: "The Vektrans have established a fortified supply corridor through the desert, funneling war materiel to their forward positions across three sectors. Intelligence estimates dozens of armored convoys moving through the region daily. Your objective: destroy their forward supply depots and cut the pipeline. Without supplies, their inland offensive stalls.",
      completionText: "Supply corridor is in ruins. Intercepted Vektran transmissions reveal their logistics network runs through a communications relay hidden in the mountain ranges to the east. That relay is coordinating movements across the entire theater. Command wants it gone — you're being rerouted to the mountains.",
      inGameMessages: [
        { triggerTime: 2, text: "Sensor: Sandstorm clearing from the scan area. Hostiles now visible on thermal.", speaker: "sensor" },
        { triggerTime: 12, text: "Wingman: Fast movers on your six — I count at least four. Breaking to engage.", speaker: "wingman" },
        { triggerTime: 21, text: "HQ: Archer, you're approaching the supply hub. Expect heavy resistance.", speaker: "hq" },
        { triggerTime: 27, text: "Sensor: Large contact emerging from behind the depot — reads as a gunship-class vessel.", speaker: "sensor" },
      ],
    },
  },
  {
    level: 3,
    name: "Mountain Assault",
    waves: [
      { enemyVariant: "scout", count: 6, spawnDelay: 0.6, waveDelay: 1, formation: "v", speed: 180 },
      { enemyVariant: "fighter", count: 4, spawnDelay: 0.8, waveDelay: 7, formation: "line", speed: 140 },
      { enemyVariant: "interceptor", count: 4, spawnDelay: 0.6, waveDelay: 11, formation: "v", speed: 250 },
      { enemyVariant: "bomber", count: 2, spawnDelay: 1.2, waveDelay: 14, formation: "random", speed: 80, weaponType: "spread" },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.5, waveDelay: 19, formation: "sweep", speed: 190 },
      { enemyVariant: "swarmer", count: 6, spawnDelay: 0.5, waveDelay: 22, formation: "random", speed: 170 },
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 25, formation: "v", speed: 150, weaponType: "spread" },
      { enemyVariant: "drone", count: 6, spawnDelay: 0.4, waveDelay: 28, formation: "random", speed: 170 },
      { enemyVariant: "bomber", count: 3, spawnDelay: 1.0, waveDelay: 32, formation: "line", speed: 90, weaponType: "spread" },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "missile_dreadnought", hitPoints: 70, speed: 30, fireRate: 1.1, scoreValue: 400, appearsAfterWave: 5, weaponType: "missile" },
    autoFireRate: 6,
    powerUpDropChance: 0.15,
    skyGradient: ["#4A6670", "#8BA8B7"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.2,
    weaponDrops: ["rocket", "laser"] as WeaponType[],
    terrain: {
      theme: "mountain",
      horizonAssets: ["horizon_mountain"],
      groundColor: "#3d5a3d",
      groundTexture: "ground_grass",
      structurePool: ["struct_pine_tree", "struct_watchtower", "struct_radar_dish", "struct_bunker"],
      structureDensity: 3,
      propPool: ["prop_rocks", "prop_debris", "prop_crater"],
      propDensity: 4,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(140, 100, 50, 0.4)",
        count: 25,
        speedRange: [10, 30],
        sizeRange: [1, 3],
        drift: 30,
      },
    },
    act: 1,
    story: {
      briefing: "A Vektran relay station buried deep in the mountain ranges is coordinating enemy troop movements across three occupied sectors. Taking it out will blind their regional command structure. The approach through the mountain pass is narrow and heavily patrolled — bomber squadrons and interceptor wings have been spotted guarding the route. Fight through and destroy the relay before they can reroute their comm network.",
      completionText: "Relay station destroyed. Our signals team managed to pull encrypted data from the wreckage before it went dark. The decrypted transmissions are troubling — they reference an experimental weapons program at an arctic research facility, along with supply manifests for technology we've never seen before. Whatever they're building up there, it isn't conventional. Command is redirecting you north.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: Entering the mountain pass now. Stay below the ridgeline as long as you can.", speaker: "hq" },
        { triggerTime: 15, text: "Sensor: Bomber squadron detected on approach vector. They're flying in formation — this is a coordinated defense.", speaker: "sensor" },
        { triggerTime: 26, text: "Wingman: I can see the relay dish through the clouds. We're almost there.", speaker: "wingman" },
        { triggerTime: 32, text: "HQ: Dreadnought-class vessel guarding the relay. Take it down, Archer.", speaker: "hq" },
      ],
    },
  },
  {
    level: 4,
    name: "Arctic Thunder",
    waves: [
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 1, formation: "line", speed: 150, weaponType: "missile" },
      { enemyVariant: "bomber", count: 3, spawnDelay: 1.0, waveDelay: 7, formation: "v", speed: 90, weaponType: "spread" },
      { enemyVariant: "gunship", count: 3, spawnDelay: 0.9, waveDelay: 10, formation: "line", speed: 110, weaponType: "spread" },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.4, waveDelay: 13, formation: "sweep", speed: 200 },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.6, waveDelay: 18, formation: "random", speed: 160, weaponType: "missile" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.3, waveDelay: 21, formation: "sweep", speed: 290 },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.9, waveDelay: 24, formation: "line", speed: 100, weaponType: "missile" },
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 31, formation: "v", speed: 150, weaponType: "missile" },
      { enemyVariant: "gunship", count: 4, spawnDelay: 0.8, waveDelay: 34, formation: "v", speed: 120, weaponType: "spread" },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 37, formation: "sweep", speed: 210 },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "laser_fortress", hitPoints: 90, speed: 20, fireRate: 1.4, scoreValue: 600, appearsAfterWave: 6, weaponType: "laser" },
    autoFireRate: 6,
    powerUpDropChance: 0.15,
    skyGradient: ["#B0C4DE", "#D3D3D3"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.4,
    weaponDrops: ["rocket", "laser", "auto-gun"] as WeaponType[],
    terrain: {
      theme: "arctic",
      horizonAssets: ["horizon_arctic"],
      groundColor: "#e0e8ee",
      groundTexture: "ground_snow",
      structurePool: ["struct_barracks", "struct_radar_dish", "struct_bunker", "struct_watchtower"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_crater", "prop_debris"],
      propDensity: 3,
      hasWater: true,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(240, 245, 255, 0.8)",
        count: 70,
        speedRange: [25, 70],
        sizeRange: [1, 3],
        drift: 25,
      },
    },
    act: 1,
    story: {
      briefing: "The Vektran arctic facility is developing weapons technology unlike anything in our arsenal — energy systems that don't match any known science. Sensor scans show heavy air defenses and experimental prototype platforms already powering up. Admiral Rennick is ordering a full strike before those prototypes go online. Visibility will be near zero. Trust your instruments and hit them hard.",
      completionText: "The arctic facility is rubble. But analysis of the recovered data has revealed something unexpected — the weapons research wasn't Vektran in origin. The schematics reference a source they call 'the Architects,' and the designs are being fed to a heavily fortified installation to the south. Intelligence believes that's where the completed superweapon is being assembled. Command wants it found and destroyed.",
      inGameMessages: [
        { triggerTime: 2, text: "Sensor: Visibility near zero. Switching to full instrument flight. I'll guide you in.", speaker: "sensor" },
        { triggerTime: 14, text: "Wingman: Missile locks! Multiple! Break right, break right!", speaker: "wingman" },
        { triggerTime: 25, text: "Sensor: Facility defense grid is weakening. Their outer ring is down.", speaker: "sensor" },
        { triggerTime: 35, text: "HQ: Rennick here. Fortress platform ahead — it's their weapons grid core. Destroy it before they evacuate those prototypes.", speaker: "hq" },
      ],
    },
  },
  {
    level: 5,
    name: "Final Fortress",
    waves: [
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.6, waveDelay: 1, formation: "v", speed: 160, weaponType: "spread" },
      { enemyVariant: "bomber", count: 3, spawnDelay: 0.9, waveDelay: 6, formation: "line", speed: 100, weaponType: "missile" },
      { enemyVariant: "stealth", count: 3, spawnDelay: 0.8, waveDelay: 9, formation: "random", speed: 160 },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 12, formation: "sweep", speed: 220 },
      { enemyVariant: "interceptor", count: 5, spawnDelay: 0.5, waveDelay: 15, formation: "v", speed: 260 },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.5, waveDelay: 17, formation: "random", speed: 170, weaponType: "missile" },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.8, waveDelay: 22, formation: "v", speed: 110, weaponType: "spread" },
      { enemyVariant: "cruiser", count: 1, spawnDelay: 0, waveDelay: 25, formation: "line", speed: 60, weaponType: "missile" },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 28, formation: "line", speed: 180, weaponType: "laser" },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 34, formation: "random", speed: 110, weaponType: "missile" },
      { enemyVariant: "swarmer", count: 8, spawnDelay: 0.4, waveDelay: 37, formation: "random", speed: 180 },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 40, formation: "sweep", speed: 230 },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "carrier", hitPoints: 100, speed: 35, fireRate: 1.5, scoreValue: 1000, appearsAfterWave: 7, weaponType: "standard" },
    autoFireRate: 7,
    powerUpDropChance: 0.18,
    skyGradient: ["#2F1B14", "#1a1a1a"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.6,
    weaponDrops: ["rocket", "laser", "auto-gun", "plasma"] as WeaponType[],
    terrain: {
      theme: "fortress",
      horizonAssets: ["horizon_fortress"],
      groundColor: "#3a3a3a",
      groundTexture: "ground_concrete",
      structurePool: [
        "struct_wall_segment", "struct_aa_gun", "struct_hangar",
        "struct_command_center", "struct_bunker",
      ],
      structureDensity: 3,
      propPool: ["prop_crater", "prop_debris", "prop_tire_tracks", "prop_rocks"],
      propDensity: 5,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(255, 140, 50, 0.5)",
        count: 40,
        speedRange: [15, 50],
        sizeRange: [0.5, 2],
        drift: 15,
      },
    },
    act: 1,
    story: {
      briefing: "Intelligence confirms the Vektran superweapon is housed inside a massive fortress complex — the most heavily defended position we've encountered. This is their last defensive line on the continent. Admiral Rennick is committing every available wing to the assault. Breach the perimeter, fight through their garrison, and secure the weapon. If we fail here, they'll have time to deploy it against the colonies.",
      completionText: "The fortress has fallen, but the superweapon bay is empty — cleared out hours before we arrived. Vektran transport logs recovered from the wreckage point to a shipyard complex behind their front lines. They moved it deeper into occupied territory, beyond our previous reach. There's no choice now. You're crossing behind enemy lines. This is the point of no return.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: Rennick to all wings — breach the perimeter. Everything we've got, right now.", speaker: "hq" },
        { triggerTime: 13, text: "Sensor: Stealth contacts on approach — I almost missed them. Watch your flanks.", speaker: "sensor" },
        { triggerTime: 23, text: "Wingman: Cruiser dead ahead! Concentrating fire — help me out here!", speaker: "wingman" },
        { triggerTime: 35, text: "HQ: Carrier-class vessel launching from the compound. All guns — take it down before it deploys its full complement!", speaker: "hq" },
        { triggerTime: 40, text: "Sensor: I'm reading hollow chambers beneath the main structure. The weapon bay — it's empty.", speaker: "sensor" },
      ],
    },
  },
  {
    level: 6,
    name: "Shipyard Ruins",
    waves: [
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.6, waveDelay: 1, formation: "line", speed: 170, weaponType: "spread" },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.8, waveDelay: 6, formation: "v", speed: 110, weaponType: "missile" },
      { enemyVariant: "destroyer", count: 1, spawnDelay: 0, waveDelay: 9, formation: "line", speed: 50, weaponType: "laser" },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 12, formation: "sweep", speed: 220 },
      { enemyVariant: "fighter", count: 7, spawnDelay: 0.5, waveDelay: 17, formation: "random", speed: 180, weaponType: "missile" },
      { enemyVariant: "stealth", count: 4, spawnDelay: 0.7, waveDelay: 20, formation: "random", speed: 170 },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 23, formation: "line", speed: 110, weaponType: "missile" },
      { enemyVariant: "minelayer", count: 2, spawnDelay: 3.0, waveDelay: 26, formation: "sweep", speed: 100 },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 29, formation: "v", speed: 190, weaponType: "missile" },
      { enemyVariant: "fighter", count: 9, spawnDelay: 0.4, waveDelay: 35, formation: "sweep", speed: 190, weaponType: "spread" },
      { enemyVariant: "gunship", count: 4, spawnDelay: 0.7, waveDelay: 38, formation: "v", speed: 120, weaponType: "spread" },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 41, formation: "sweep", speed: 230 },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 47, formation: "random", speed: 120, weaponType: "missile" },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "missile_dreadnought", hitPoints: 180, speed: 25, fireRate: 1.6, scoreValue: 1200, appearsAfterWave: 7, weaponType: "missile" },
    autoFireRate: 7,
    powerUpDropChance: 0.18,
    skyGradient: ["#2b1d1d", "#4a3333"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.8,
    weaponDrops: ["rocket", "laser", "plasma", "ion-cannon", "missile"] as WeaponType[],
    terrain: {
      theme: "shipyard",
      horizonAssets: ["horizon_shipyard"],
      groundColor: "#3a2f2a",
      groundTexture: "ground_rust",
      structurePool: ["struct_crane", "struct_drydock", "struct_ship_hull", "struct_cargo_container"],
      structureDensity: 3,
      propPool: ["prop_scrap_metal", "prop_oil_drum", "prop_debris", "prop_anchor"],
      propDensity: 5,
      hasWater: true,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(180, 120, 60, 0.5)",
        count: 35,
        speedRange: [10, 35],
        sizeRange: [0.5, 2],
        drift: 15,
      },
      hazeColor: "rgba(60, 40, 30, 1)",
      hazeOpacity: 0.12,
      secondaryParticles: {
        color: "rgba(160, 150, 140, 0.5)",
        count: 30,
        speedRange: [15, 40],
        sizeRange: [1, 3],
        drift: 20,
      },
      litStructures: ["struct_crane", "struct_drydock"],
    },
    act: 1,
    story: {
      briefing: "You've crossed behind enemy lines into territory no allied pilot has seen and returned from. The Vektran shipyard ahead is churning out warships at an alarming rate — if left unchecked, their fleet will double within weeks. Destroy the drydocks and assembly platforms. Be warned: you're operating without support. No extraction, no reinforcements. Whatever you find in there, you handle alone.",
      completionText: "The shipyard is a smoking ruin. Dozens of half-built warships will never see combat. But recon drones sent ahead report only devastation — scorched wastelands stretching to the horizon, littered with the wreckage of earlier offensives that never made it this far. The Vektrans have been fighting someone else here, or perhaps testing their weapons. Either way, the only path forward runs through the graveyard.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: You're behind enemy lines now, Archer. Comms will be intermittent. Good luck.", speaker: "hq" },
        { triggerTime: 10, text: "Sensor: Destroyer-class contact on intercept course. Heavily armed.", speaker: "sensor" },
        { triggerTime: 21, text: "Wingman: Mines in the channel — stay high and watch your altitude.", speaker: "wingman" },
        { triggerTime: 30, text: "Sensor: I'm picking up energy signatures from the drydocks. Some of these ships are nearly complete.", speaker: "sensor" },
        { triggerTime: 38, text: "HQ: Dreadnought-class vessel emerging from the drydocks. It's armed and heading your way, Archer.", speaker: "hq" },
      ],
    },
  },
  {
    level: 7,
    name: "Scorched Wastes",
    waves: [
      { enemyVariant: "fighter", count: 7, spawnDelay: 0.5, waveDelay: 1, formation: "v", speed: 180, weaponType: "missile" },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.8, waveDelay: 6, formation: "line", speed: 110, weaponType: "spread" },
      { enemyVariant: "gunship", count: 4, spawnDelay: 0.7, waveDelay: 8, formation: "line", speed: 120, weaponType: "spread" },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 11, formation: "sweep", speed: 230 },
      { enemyVariant: "drone", count: 8, spawnDelay: 0.3, waveDelay: 14, formation: "random", speed: 180 },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 16, formation: "random", speed: 190, weaponType: "missile" },
      { enemyVariant: "bomber", count: 3, spawnDelay: 0.9, waveDelay: 16, formation: "line", speed: 110, weaponType: "missile" },
      { enemyVariant: "cruiser", count: 2, spawnDelay: 2.0, waveDelay: 20, formation: "line", speed: 65, weaponType: "missile" },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 23, formation: "v", speed: 120, weaponType: "missile" },
      { enemyVariant: "interceptor", count: 6, spawnDelay: 0.4, waveDelay: 26, formation: "v", speed: 260 },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 29, formation: "line", speed: 240 },
      { enemyVariant: "swarmer", count: 6, spawnDelay: 0.4, waveDelay: 31, formation: "random", speed: 180 },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.5, waveDelay: 34, formation: "sweep", speed: 180, weaponType: "missile" },
      { enemyVariant: "minelayer", count: 1, spawnDelay: 0, waveDelay: 37, formation: "sweep", speed: 100 },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 40, formation: "random", speed: 120, weaponType: "spread" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.3, waveDelay: 43, formation: "sweep", speed: 290 },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 46, formation: "sweep", speed: 240 },
      { enemyVariant: "destroyer", count: 1, spawnDelay: 0, waveDelay: 49, formation: "line", speed: 50, weaponType: "laser" },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "laser_fortress", hitPoints: 220, speed: 18, fireRate: 2.0, scoreValue: 1500, appearsAfterWave: 8, weaponType: "laser" },
    autoFireRate: 8,
    powerUpDropChance: 0.19,
    skyGradient: ["#1a1a0e", "#3d3520"],
    starDensity: 0,
    enemyFireRateMultiplier: 2.0,
    weaponDrops: ["rocket", "laser", "plasma", "ion-cannon", "missile"] as WeaponType[],
    terrain: {
      theme: "wasteland",
      horizonAssets: ["horizon_wasteland"],
      groundColor: "#2e2a1e",
      groundTexture: "ground_ash",
      structurePool: ["struct_ruin", "struct_dead_tree", "struct_wrecked_tank", "struct_bunker"],
      structureDensity: 2,
      propPool: ["prop_crater", "prop_bones", "prop_radiation_sign", "prop_debris"],
      propDensity: 5,
      hasWater: false,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(100, 90, 60, 0.6)",
        count: 60,
        speedRange: [15, 50],
        sizeRange: [0.5, 3],
        drift: 35,
      },
      hazeColor: "rgba(80, 60, 20, 1)",
      hazeOpacity: 0.15,
      secondaryParticles: {
        color: "rgba(255, 140, 40, 0.7)",
        count: 40,
        speedRange: [-40, -15],
        sizeRange: [1, 2.5],
        drift: 10,
      },
      litStructures: ["struct_ruin", "struct_wrecked_tank"],
    },
    act: 1,
    story: {
      briefing: "The scorched wastelands ahead are a graveyard — the remains of previous allied offensives that tried to reach the Vektran heartland and failed. Wreckage from dozens of engagements litters the terrain. Heavy Vektran patrols guard the approach, and they fight like they're protecting something critical beyond. Push through the kill zone and clear the way to their industrial core. The cost of this war is written in the ground below you.",
      completionText: "The wasteland is behind you, but the losses were staggering. Thermal scans of the region ahead reveal massive energy output — factory complexes and reactor systems running at full capacity. This is the Vektran industrial core, and intelligence now believes the superweapon is being assembled inside. But something else showed up in the scan data: the energy signatures don't match Vektran technology. Something else is powering their war machine.",
      inGameMessages: [
        { triggerTime: 2, text: "Sensor: Radiation levels climbing. The ground below is scorched — old battlefields.", speaker: "sensor" },
        { triggerTime: 12, text: "Sensor: Multiple cruiser-class contacts on approach. They're running in formation.", speaker: "sensor" },
        { triggerTime: 27, text: "Wingman: They're throwing everything at us. I've never seen this many in one sector.", speaker: "wingman" },
        { triggerTime: 35, text: "HQ: ...signal's breaking up... hold your course, Archer...", speaker: "hq" },
        { triggerTime: 42, text: "Sensor: Fortress platform detected on the far edge. It's powering up its beam arrays.", speaker: "sensor" },
      ],
    },
  },
  {
    level: 8,
    name: "Industrial Core",
    waves: [
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.5, waveDelay: 1, formation: "line", speed: 190, weaponType: "missile" },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 6, formation: "v", speed: 120, weaponType: "missile" },
      { enemyVariant: "destroyer", count: 2, spawnDelay: 3.0, waveDelay: 9, formation: "line", speed: 50, weaponType: "laser" },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 11, formation: "sweep", speed: 240 },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 16, formation: "random", speed: 200, weaponType: "laser" },
      { enemyVariant: "stealth", count: 4, spawnDelay: 0.6, waveDelay: 19, formation: "random", speed: 180 },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 21, formation: "line", speed: 130, weaponType: "missile" },
      { enemyVariant: "minelayer", count: 1, spawnDelay: 0, waveDelay: 24, formation: "sweep", speed: 100 },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.35, waveDelay: 27, formation: "v", speed: 200, weaponType: "missile" },
      { enemyVariant: "cruiser", count: 2, spawnDelay: 2.0, waveDelay: 30, formation: "line", speed: 65, weaponType: "missile" },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 33, formation: "random", speed: 120, weaponType: "missile" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.3, waveDelay: 36, formation: "sweep", speed: 290 },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 39, formation: "sweep", speed: 250 },
      { enemyVariant: "gunship", count: 5, spawnDelay: 0.6, waveDelay: 42, formation: "v", speed: 130, weaponType: "spread" },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 45, formation: "line", speed: 200, weaponType: "laser" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 48, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "bomber", count: 7, spawnDelay: 0.5, waveDelay: 51, formation: "v", speed: 130, weaponType: "missile" },
      { enemyVariant: "swarmer", count: 6, spawnDelay: 0.4, waveDelay: 54, formation: "random", speed: 180 },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "carrier", hitPoints: 230, speed: 32, fireRate: 2.2, scoreValue: 2000, appearsAfterWave: 8, weaponType: "standard" },
    autoFireRate: 8,
    powerUpDropChance: 0.19,
    skyGradient: ["#1c1c1c", "#333030"],
    starDensity: 0,
    enemyFireRateMultiplier: 2.2,
    weaponDrops: ["rocket", "laser", "plasma", "ion-cannon", "missile"] as WeaponType[],
    terrain: {
      theme: "industrial",
      horizonAssets: ["horizon_industrial"],
      groundColor: "#2a2a2a",
      groundTexture: "ground_metal",
      structurePool: ["struct_smokestack", "struct_factory", "struct_conveyor", "struct_cooling_tower", "struct_pipe_cluster"],
      structureDensity: 4,
      propPool: ["prop_oil_drum", "prop_debris", "prop_grate", "prop_steam_vent"],
      propDensity: 6,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(80, 80, 80, 0.7)",
        count: 55,
        speedRange: [20, 60],
        sizeRange: [1, 3],
        drift: 10,
      },
      hazeColor: "rgba(50, 50, 50, 1)",
      hazeOpacity: 0.18,
      secondaryParticles: {
        color: "rgba(255, 100, 20, 0.7)",
        count: 50,
        speedRange: [-40, -15],
        sizeRange: [0.5, 2],
        drift: 8,
      },
      scanlines: true,
      litStructures: ["struct_smokestack", "struct_factory", "struct_cooling_tower"],
    },
    act: 1,
    story: {
      briefing: "The Vektran industrial core powers their entire war machine — factories, reactor complexes, and assembly lines running around the clock. Crippling this facility will cut off superweapon production and starve their forces of materiel. But the defenses here are the heaviest you've faced: juggernauts, destroyer squadrons, and automated defense grids. Admiral Rennick is counting on you to tear the heart out of their operation.",
      completionText: "The industrial core is crippled. Reactors are in meltdown and the assembly lines are slag. Without their factories, the Vektrans can't rebuild or resupply. But as the smoke clears, sensor data confirms the worst — the Vektran command core has evacuated to an orbital station. They saw this coming and pulled their leadership off-world. If we want to end this, we have to follow them into orbit.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: Industrial core in sight. This is the backbone of their war effort — hit it hard.", speaker: "hq" },
        { triggerTime: 10, text: "Sensor: Destroyer squadron on intercept. Two contacts, closing fast.", speaker: "sensor" },
        { triggerTime: 25, text: "Wingman: Juggernaut on approach — that thing has more armor than a cruiser. Watch the missiles!", speaker: "wingman" },
        { triggerTime: 38, text: "Sensor: Carrier-class vessel launching from the assembly bay. It's deploying drones!", speaker: "sensor" },
        { triggerTime: 45, text: "HQ: Reactors are destabilizing. Keep firing — don't let them save anything!", speaker: "hq" },
      ],
    },
  },
  {
    level: 9,
    name: "Orbital Debris",
    waves: [
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 1, formation: "v", speed: 200, weaponType: "laser" },
      { enemyVariant: "interceptor", count: 6, spawnDelay: 0.4, waveDelay: 4, formation: "v", speed: 270 },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 6, formation: "line", speed: 130, weaponType: "missile" },
      { enemyVariant: "drone", count: 10, spawnDelay: 0.25, waveDelay: 9, formation: "random", speed: 190 },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 11, formation: "sweep", speed: 250 },
      { enemyVariant: "swarmer", count: 8, spawnDelay: 0.35, waveDelay: 14, formation: "random", speed: 190 },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.35, waveDelay: 16, formation: "random", speed: 200, weaponType: "missile" },
      { enemyVariant: "destroyer", count: 2, spawnDelay: 3.0, waveDelay: 19, formation: "line", speed: 55, weaponType: "laser" },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 21, formation: "v", speed: 130, weaponType: "laser" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.3, waveDelay: 24, formation: "sweep", speed: 290 },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 27, formation: "line", speed: 250 },
      { enemyVariant: "cruiser", count: 2, spawnDelay: 2.0, waveDelay: 30, formation: "line", speed: 65, weaponType: "missile" },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.35, waveDelay: 33, formation: "sweep", speed: 200, weaponType: "missile" },
      { enemyVariant: "stealth", count: 5, spawnDelay: 0.5, waveDelay: 36, formation: "random", speed: 180 },
      { enemyVariant: "bomber", count: 7, spawnDelay: 0.5, waveDelay: 39, formation: "random", speed: 130, weaponType: "missile" },
      { enemyVariant: "minelayer", count: 1, spawnDelay: 0, waveDelay: 42, formation: "sweep", speed: 100 },
      { enemyVariant: "scout", count: 16, spawnDelay: 0.18, waveDelay: 45, formation: "sweep", speed: 250 },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.3, waveDelay: 51, formation: "v", speed: 200, weaponType: "laser" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 54, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "bomber", count: 8, spawnDelay: 0.4, waveDelay: 57, formation: "line", speed: 130, weaponType: "laser" },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "gunship_commander", hitPoints: 280, speed: 55, fireRate: 2.5, scoreValue: 2500, appearsAfterWave: 9, weaponType: "spread" },
    autoFireRate: 9,
    powerUpDropChance: 0.19,
    skyGradient: ["#050510", "#0a0a20"],
    starDensity: 40,
    enemyFireRateMultiplier: 2.4,
    weaponDrops: ["rocket", "laser", "plasma", "ion-cannon", "missile"] as WeaponType[],
    terrain: {
      theme: "orbital",
      horizonAssets: ["horizon_orbital"],
      groundColor: "#0c0c14",
      groundTexture: "ground_hull_plate",
      structurePool: ["struct_satellite_dish", "struct_solar_panel", "struct_station_module", "struct_antenna_array"],
      structureDensity: 3,
      propPool: ["prop_space_debris", "prop_hull_fragment", "prop_wiring", "prop_panel_shard"],
      propDensity: 6,
      hasWater: false,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(150, 180, 255, 0.4)",
        count: 30,
        speedRange: [5, 20],
        sizeRange: [0.5, 1.5],
        drift: 5,
      },
      hazeColor: "rgba(10, 10, 30, 1)",
      hazeOpacity: 0.08,
      secondaryParticles: {
        color: "rgba(180, 200, 255, 0.6)",
        count: 25,
        speedRange: [-10, 10],
        sizeRange: [0.5, 1.5],
        drift: 15,
      },
      scanlines: true,
      litStructures: ["struct_station_module", "struct_antenna_array"],
    },
    act: 1,
    story: {
      briefing: "The Vektran command core has retreated to an orbital station hidden within a massive debris field — the remains of humanity's first fleet, destroyed in the opening hours of the invasion. Navigate through the wreckage of our own ships and punch through their orbital defense network. This is the penultimate push. Every wing that can still fly is converging on this position. Clear the way for the final assault.",
      completionText: "Orbital defenses are shattered. Through the thinning debris, the Vektran Stronghold comes into view — a massive station bristling with weapons, its reactor core pulsing with that same alien energy signature. All remaining allied forces are converging. Admiral Rennick is committing everything to one final strike. This is it. Whatever answers the Vektrans are hiding, they're inside that station.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: You've reached orbit, Archer. Fly careful — this debris field is what's left of the Third Fleet.", speaker: "hq" },
        { triggerTime: 10, text: "Sensor: Swarm contacts everywhere. Drones, fighters, interceptors — the whole screen is lit up.", speaker: "sensor" },
        { triggerTime: 22, text: "Wingman: This wreckage... these are our ships. The ones from the first wave.", speaker: "wingman" },
        { triggerTime: 30, text: "Wingman: Destroyers blocking the approach lane. I'm engaging — cover my wing.", speaker: "wingman" },
        { triggerTime: 46, text: "Sensor: Gunship commander detected — extreme speed, heavy spread weapons. Brace yourself, Archer.", speaker: "sensor" },
      ],
    },
  },
  {
    level: 10,
    name: "Vektran Stronghold",
    waves: [
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.35, waveDelay: 1, formation: "line", speed: 200, weaponType: "laser" },
      { enemyVariant: "dart", count: 10, spawnDelay: 0.25, waveDelay: 4, formation: "sweep", speed: 300 },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 6, formation: "v", speed: 130, weaponType: "missile" },
      { enemyVariant: "gunship", count: 5, spawnDelay: 0.6, waveDelay: 9, formation: "line", speed: 130, weaponType: "spread" },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 11, formation: "sweep", speed: 250 },
      { enemyVariant: "cruiser", count: 2, spawnDelay: 2.0, waveDelay: 14, formation: "line", speed: 65, weaponType: "missile" },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.3, waveDelay: 16, formation: "random", speed: 200, weaponType: "missile" },
      { enemyVariant: "bomber", count: 7, spawnDelay: 0.5, waveDelay: 21, formation: "line", speed: 130, weaponType: "laser" },
      { enemyVariant: "destroyer", count: 2, spawnDelay: 3.0, waveDelay: 24, formation: "line", speed: 55, weaponType: "laser" },
      { enemyVariant: "fighter", count: 12, spawnDelay: 0.3, waveDelay: 27, formation: "v", speed: 200, weaponType: "laser" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 30, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "scout", count: 16, spawnDelay: 0.18, waveDelay: 33, formation: "sweep", speed: 250 },
      { enemyVariant: "minelayer", count: 2, spawnDelay: 3.0, waveDelay: 36, formation: "sweep", speed: 110 },
      { enemyVariant: "bomber", count: 8, spawnDelay: 0.5, waveDelay: 39, formation: "random", speed: 130, weaponType: "missile" },
      { enemyVariant: "fighter", count: 12, spawnDelay: 0.25, waveDelay: 45, formation: "line", speed: 200, weaponType: "missile" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 48, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "scout", count: 18, spawnDelay: 0.15, waveDelay: 51, formation: "sweep", speed: 250 },
      { enemyVariant: "bomber", count: 8, spawnDelay: 0.4, waveDelay: 57, formation: "v", speed: 130, weaponType: "laser" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 60, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "fighter", count: 14, spawnDelay: 0.2, waveDelay: 63, formation: "line", speed: 200, weaponType: "laser" },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "standard", hitPoints: 400, speed: 25, fireRate: 2.8, scoreValue: 3000, appearsAfterWave: 10, weaponType: "laser" },
    autoFireRate: 9,
    powerUpDropChance: 0.20,
    skyGradient: ["#0a0000", "#1a0505"],
    starDensity: 50,
    enemyFireRateMultiplier: 2.5,
    weaponDrops: ["rocket", "laser", "plasma", "ion-cannon", "missile"] as WeaponType[],
    terrain: {
      theme: "stronghold",
      horizonAssets: ["horizon_stronghold"],
      groundColor: "#1a1a1a",
      groundTexture: "ground_dark_metal",
      structurePool: ["struct_vektran_tower", "struct_turret_base", "struct_heavy_gate", "struct_reactor_core", "struct_aa_gun"],
      structureDensity: 4,
      propPool: ["prop_red_light", "prop_debris", "prop_cable_cluster", "prop_vent_grate", "prop_blast_mark"],
      propDensity: 7,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(255, 40, 40, 0.4)",
        count: 45,
        speedRange: [10, 40],
        sizeRange: [0.5, 2],
        drift: 8,
      },
      hazeColor: "rgba(40, 5, 5, 1)",
      hazeOpacity: 0.20,
      secondaryParticles: {
        color: "rgba(255, 60, 20, 0.7)",
        count: 60,
        speedRange: [-40, -15],
        sizeRange: [0.5, 2],
        drift: 10,
      },
      scanlines: true,
      litStructures: ["struct_vektran_tower", "struct_reactor_core", "struct_turret_base"],
    },
    act: 1,
    story: {
      briefing: "The Vektran Stronghold. Their central command core is buried deep inside this orbital fortress. Every enemy unit in the theater is connected to this station — destroy the core and their entire network collapses. Admiral Rennick is committing every remaining allied ship to this assault. There will be no retreat. All wings: begin the final assault on the Vektran command.",
      completionText: "The command core is destroyed. Across the colonies, Vektran forces are going dark — cut off from their central intelligence. Against impossible odds, you've broken their hold on human space. But in the core's final data burst, your sensors captured something that changes everything. A transmission, aimed not at Vektran forces — but outward, toward deep space. A signal to something far larger than anything you've fought today.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: Admiral Rennick to all wings — commence attack. This is what we've been fighting for.", speaker: "hq" },
        { triggerTime: 12, text: "Sensor: Cruisers and juggernauts on intercept. They're deploying everything they have left.", speaker: "sensor" },
        { triggerTime: 28, text: "Wingman: Juggernaut is down! Don't stop — keep pushing toward the core!", speaker: "wingman" },
        { triggerTime: 42, text: "Sensor: I'm reading a massive energy buildup inside the station. The core — it's exposed.", speaker: "sensor" },
        { triggerTime: 48, text: "HQ: Command core is exposed! All guns on that target — hit it now!", speaker: "hq" },
        { triggerTime: 60, text: "HQ: Final wave incoming — give it everything you've got! This ends here!", speaker: "hq" },
      ],
    },
  },
  {
    level: 11,
    name: "Colony Defense",
    waves: [
      { enemyVariant: "scout", count: 6, spawnDelay: 0.7, waveDelay: 1, formation: "line", speed: 180 },
      { enemyVariant: "fighter", count: 4, spawnDelay: 0.9, waveDelay: 7, formation: "v", speed: 140 },
      { enemyVariant: "dart", count: 6, spawnDelay: 0.5, waveDelay: 11, formation: "sweep", speed: 220 },
      { enemyVariant: "interceptor", count: 5, spawnDelay: 0.6, waveDelay: 15, formation: "v", speed: 200 },
      { enemyVariant: "stealth", count: 3, spawnDelay: 0.8, waveDelay: 19, formation: "random", speed: 170 },
      { enemyVariant: "swarmer", count: 4, spawnDelay: 0.6, waveDelay: 19, formation: "random", speed: 170 },
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 24, formation: "line", speed: 160, weaponType: "missile" },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.4, waveDelay: 28, formation: "sweep", speed: 200 },
      { enemyVariant: "bomber", count: 3, spawnDelay: 1.0, waveDelay: 32, formation: "v", speed: 100 },
      { enemyVariant: "dart", count: 6, spawnDelay: 0.4, waveDelay: 36, formation: "sweep", speed: 230 },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "missile_dreadnought", hitPoints: 120, speed: 30, fireRate: 1.2, scoreValue: 800, appearsAfterWave: 6, weaponType: "missile" },
    autoFireRate: 6,
    powerUpDropChance: 0.15,
    skyGradient: ["#1a1a3e", "#4a3060"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.4,
    weaponDrops: ["rocket", "laser", "auto-gun"] as WeaponType[],
    terrain: {
      theme: "colony",
      horizonAssets: ["horizon_colony"],
      groundColor: "#5a5a6e",
      groundTexture: "ground_concrete",
      structurePool: ["struct_colony_tower", "struct_landing_pad", "struct_comm_relay", "struct_habitat"],
      structureDensity: 3,
      propPool: ["prop_debris", "prop_crate", "prop_antenna", "prop_light_post"],
      propDensity: 4,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(255, 180, 80, 0.5)",
        count: 35,
        speedRange: [10, 35],
        sizeRange: [0.5, 2],
        drift: 15,
      },
      hazeColor: "rgba(40, 30, 60, 1)",
      hazeOpacity: 0.10,
      litStructures: ["struct_colony_tower", "struct_comm_relay"],
    },
    act: 2,
    story: {
      briefing: "The Vektrans are gone, but something worse has taken their place. Unidentified scouts — faster and more advanced than anything in the Vektran arsenal — are hitting Colony Meridian. Admiral Rennick has confirmed what intelligence feared: this is the Dominion, the civilization the Vektrans were fleeing from. Defend the colony and buy time for civilian evacuation.",
      completionText: "Colony Meridian is secure, but the cost was high. Sensor analysis of the downed scouts reveals their origin — a staging area hidden in the asteroid belt on the system's edge. The Dominion didn't stumble onto us. They came prepared. Command is scrambling a strike force to hit their staging area before the next wave launches.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: Rennick here. We've got unidentified contacts inbound on Colony Meridian. This isn't Vektran tech — it's something new.", speaker: "hq" },
        { triggerTime: 8, text: "Sensor: Confirmed — energy signatures don't match any Vektran profile. These are Dominion scouts.", speaker: "sensor" },
        { triggerTime: 18, text: "Wingman: Stealth and swarmer contacts at the same time — they're coordinating like nothing we've seen!", speaker: "wingman" },
        { triggerTime: 30, text: "Sensor: Massive energy signature emerging from the cloud layer. Dreadnought-class — Dominion configuration.", speaker: "sensor" },
        { triggerTime: 35, text: "HQ: That dreadnought is heading for the colony center. Take it down, Archer — the civilians are counting on us.", speaker: "hq" },
      ],
    },
  },
  {
    level: 12,
    name: "Asteroid Ambush",
    waves: [
      { enemyVariant: "dart", count: 7, spawnDelay: 0.4, waveDelay: 1, formation: "sweep", speed: 230 },
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 5, formation: "v", speed: 160, weaponType: "missile" },
      { enemyVariant: "interceptor", count: 6, spawnDelay: 0.5, waveDelay: 9, formation: "v", speed: 220 },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.4, waveDelay: 13, formation: "sweep", speed: 200 },
      { enemyVariant: "cruiser", count: 1, spawnDelay: 0, waveDelay: 17, formation: "line", speed: 60, weaponType: "missile" },
      { enemyVariant: "fighter", count: 4, spawnDelay: 0.7, waveDelay: 17, formation: "line", speed: 170, weaponType: "missile" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.35, waveDelay: 22, formation: "sweep", speed: 250 },
      { enemyVariant: "swarmer", count: 6, spawnDelay: 0.5, waveDelay: 26, formation: "random", speed: 180 },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.8, waveDelay: 30, formation: "line", speed: 110, weaponType: "missile" },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.5, waveDelay: 34, formation: "random", speed: 180, weaponType: "laser" },
      { enemyVariant: "interceptor", count: 4, spawnDelay: 0.5, waveDelay: 34, formation: "v", speed: 240 },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 38, formation: "sweep", speed: 220 },
    ],
    bossEnabled: true,
    bossConfig: { bossType: "laser_fortress", hitPoints: 150, speed: 18, fireRate: 1.4, scoreValue: 1000, appearsAfterWave: 7, weaponType: "laser" },
    autoFireRate: 7,
    powerUpDropChance: 0.16,
    skyGradient: ["#050508", "#0f0f1a"],
    starDensity: 30,
    enemyFireRateMultiplier: 1.6,
    weaponDrops: ["rocket", "laser", "auto-gun", "plasma"] as WeaponType[],
    terrain: {
      theme: "asteroid",
      horizonAssets: ["horizon_asteroid"],
      groundColor: "#1a1a1e",
      groundTexture: "ground_rock",
      structurePool: ["struct_drill_rig", "struct_ore_processor", "struct_cargo_pod", "struct_beacon"],
      structureDensity: 2,
      propPool: ["prop_asteroid_chunk", "prop_space_debris", "prop_hull_fragment", "prop_cable_cluster"],
      propDensity: 5,
      hasWater: false,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(160, 180, 220, 0.4)",
        count: 40,
        speedRange: [8, 25],
        sizeRange: [0.5, 2.5],
        drift: 12,
      },
      hazeColor: "rgba(5, 5, 15, 1)",
      hazeOpacity: 0.08,
      litStructures: ["struct_beacon", "struct_ore_processor"],
    },
    act: 2,
    story: {
      briefing: "Sensor data from the Colony Meridian engagement traced the Dominion scouts back to a staging area in the outer asteroid belt. Command wants it destroyed before they can launch a full-scale assault on the inner colonies. Expect heavy resistance — the asteroid field gives them natural cover, and they know we're coming.",
      completionText: "The staging area is destroyed, but long-range scans have detected something far worse. A dense nebula at the system's edge is concealing a massive Dominion fleet — hundreds of ships, waiting. The scouts and the staging area were just the vanguard. Whatever the Dominion is planning, the real fight hasn't started yet.",
      inGameMessages: [
        { triggerTime: 2, text: "HQ: Entering the asteroid belt. Stay sharp — they've had time to prepare positions in here.", speaker: "hq" },
        { triggerTime: 10, text: "Sensor: Multiple fast contacts weaving through the rocks. Darts and interceptors — they're using the asteroids as cover.", speaker: "sensor" },
        { triggerTime: 18, text: "Wingman: Cruiser anchored behind that rock cluster — fighters screening it. Hit the escorts first!", speaker: "wingman" },
        { triggerTime: 32, text: "Sensor: Massive energy buildup detected ahead. Fortress-class platform — it's powering up its beam arrays.", speaker: "sensor" },
        { triggerTime: 40, text: "HQ: That fortress is the lynchpin of their staging area. Destroy it and we cut off their forward operations.", speaker: "hq" },
      ],
    },
  },
];
