import { RaptorLevelConfig, WeaponType } from "./types";

export const LEVELS: RaptorLevelConfig[] = [
  {
    level: 1,
    name: "Coastal Patrol",
    waves: [
      { enemyVariant: "scout", count: 5, spawnDelay: 0.8, waveDelay: 1, formation: "line", speed: 150 },
      { enemyVariant: "scout", count: 6, spawnDelay: 0.7, waveDelay: 8, formation: "v", speed: 160 },
      { enemyVariant: "scout", count: 5, spawnDelay: 0.6, waveDelay: 15, formation: "random", speed: 170 },
      { enemyVariant: "scout", count: 7, spawnDelay: 0.5, waveDelay: 22, formation: "sweep", speed: 180 },
    ],
    bossEnabled: false,
    autoFireRate: 5,
    powerUpDropChance: 0.10,
    skyGradient: ["#87CEEB", "#E0F0FF"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.0,
    terrain: {
      theme: "coastal",
      horizonAssets: ["horizon_coastal"],
      groundColor: "#4d8c3f",
      groundTexture: "ground_grass",
      structurePool: ["struct_beach_hut", "struct_lighthouse", "struct_palm_tree"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_debris"],
      propDensity: 3,
      hasWater: true,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(200, 230, 255, 0.6)",
        count: 30,
        speedRange: [15, 40],
        sizeRange: [1, 2.5],
        drift: 20,
      },
    },
  },
  {
    level: 2,
    name: "Desert Strike",
    waves: [
      { enemyVariant: "scout", count: 5, spawnDelay: 0.7, waveDelay: 1, formation: "line", speed: 170 },
      { enemyVariant: "fighter", count: 3, spawnDelay: 1.0, waveDelay: 7, formation: "v", speed: 120 },
      { enemyVariant: "scout", count: 6, spawnDelay: 0.6, waveDelay: 14, formation: "sweep", speed: 180 },
      { enemyVariant: "fighter", count: 4, spawnDelay: 0.9, waveDelay: 20, formation: "random", speed: 130 },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.5, waveDelay: 28, formation: "line", speed: 190 },
    ],
    bossEnabled: false,
    autoFireRate: 5,
    powerUpDropChance: 0.12,
    skyGradient: ["#F4A460", "#87CEEB"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.0,
    weaponDrops: ["missile"] as WeaponType[],
    terrain: {
      theme: "desert",
      horizonAssets: ["horizon_desert"],
      groundColor: "#c8a060",
      groundTexture: "ground_sand",
      structurePool: ["struct_oil_rig", "struct_cactus", "struct_bunker"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_crater", "prop_tire_tracks"],
      propDensity: 4,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(210, 180, 120, 0.5)",
        count: 50,
        speedRange: [20, 60],
        sizeRange: [0.5, 2],
        drift: 40,
      },
    },
  },
  {
    level: 3,
    name: "Mountain Assault",
    waves: [
      { enemyVariant: "scout", count: 6, spawnDelay: 0.6, waveDelay: 1, formation: "v", speed: 180 },
      { enemyVariant: "fighter", count: 4, spawnDelay: 0.8, waveDelay: 7, formation: "line", speed: 140 },
      { enemyVariant: "bomber", count: 2, spawnDelay: 1.2, waveDelay: 14, formation: "random", speed: 80 },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.5, waveDelay: 19, formation: "sweep", speed: 190 },
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 25, formation: "v", speed: 150 },
      { enemyVariant: "bomber", count: 3, spawnDelay: 1.0, waveDelay: 32, formation: "line", speed: 90 },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 20, speed: 40, fireRate: 1.2, scoreValue: 200, appearsAfterWave: 5 },
    autoFireRate: 6,
    powerUpDropChance: 0.15,
    skyGradient: ["#4A6670", "#8BA8B7"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.2,
    weaponDrops: ["missile", "laser"] as WeaponType[],
    terrain: {
      theme: "mountain",
      horizonAssets: ["horizon_mountain"],
      groundColor: "#3d5a3d",
      groundTexture: "ground_grass",
      structurePool: ["struct_pine_tree", "struct_watchtower", "struct_radar_dish", "struct_bunker"],
      structureDensity: 3,
      propPool: ["prop_rocks", "prop_debris", "prop_crater"],
      propDensity: 4,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(140, 100, 50, 0.4)",
        count: 25,
        speedRange: [10, 30],
        sizeRange: [1, 3],
        drift: 30,
      },
    },
  },
  {
    level: 4,
    name: "Arctic Thunder",
    waves: [
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 1, formation: "line", speed: 150 },
      { enemyVariant: "bomber", count: 3, spawnDelay: 1.0, waveDelay: 7, formation: "v", speed: 90 },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.4, waveDelay: 13, formation: "sweep", speed: 200 },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.6, waveDelay: 18, formation: "random", speed: 160 },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.9, waveDelay: 24, formation: "line", speed: 100 },
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 31, formation: "v", speed: 150 },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 37, formation: "sweep", speed: 210 },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 30, speed: 35, fireRate: 1.5, scoreValue: 300, appearsAfterWave: 6 },
    autoFireRate: 6,
    powerUpDropChance: 0.15,
    skyGradient: ["#B0C4DE", "#D3D3D3"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.4,
    weaponDrops: ["missile", "laser"] as WeaponType[],
    terrain: {
      theme: "arctic",
      horizonAssets: ["horizon_arctic"],
      groundColor: "#e0e8ee",
      groundTexture: "ground_snow",
      structurePool: ["struct_barracks", "struct_radar_dish", "struct_bunker", "struct_watchtower"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_crater", "prop_debris"],
      propDensity: 3,
      hasWater: true,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(240, 245, 255, 0.8)",
        count: 70,
        speedRange: [25, 70],
        sizeRange: [1, 3],
        drift: 25,
      },
    },
  },
  {
    level: 5,
    name: "Final Fortress",
    waves: [
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.6, waveDelay: 1, formation: "v", speed: 160 },
      { enemyVariant: "bomber", count: 3, spawnDelay: 0.9, waveDelay: 6, formation: "line", speed: 100 },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 12, formation: "sweep", speed: 220 },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.5, waveDelay: 17, formation: "random", speed: 170 },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.8, waveDelay: 22, formation: "v", speed: 110 },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 28, formation: "line", speed: 180 },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 34, formation: "random", speed: 110 },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 40, formation: "sweep", speed: 230 },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 50, speed: 30, fireRate: 2.0, scoreValue: 500, appearsAfterWave: 7 },
    autoFireRate: 7,
    powerUpDropChance: 0.18,
    skyGradient: ["#2F1B14", "#1a1a1a"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.6,
    weaponDrops: ["missile", "laser"] as WeaponType[],
    terrain: {
      theme: "fortress",
      horizonAssets: ["horizon_fortress"],
      groundColor: "#3a3a3a",
      groundTexture: "ground_concrete",
      structurePool: [
        "struct_wall_segment", "struct_aa_gun", "struct_hangar",
        "struct_command_center", "struct_bunker",
      ],
      structureDensity: 3,
      propPool: ["prop_crater", "prop_debris", "prop_tire_tracks", "prop_rocks"],
      propDensity: 5,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(255, 140, 50, 0.5)",
        count: 40,
        speedRange: [15, 50],
        sizeRange: [0.5, 2],
        drift: 15,
      },
    },
  },
];
