import { RaptorLevelConfig, WeaponType } from "./types";

export const LEVELS: RaptorLevelConfig[] = [
  {
    level: 1,
    name: "Coastal Patrol",
    waves: [
      { enemyVariant: "scout", count: 5, spawnDelay: 0.8, waveDelay: 1, formation: "line", speed: 150 },
      { enemyVariant: "scout", count: 6, spawnDelay: 0.7, waveDelay: 8, formation: "v", speed: 160 },
      { enemyVariant: "scout", count: 5, spawnDelay: 0.6, waveDelay: 15, formation: "random", speed: 170 },
      { enemyVariant: "drone", count: 7, spawnDelay: 0.4, waveDelay: 18, formation: "random", speed: 160 },
      { enemyVariant: "scout", count: 7, spawnDelay: 0.5, waveDelay: 22, formation: "sweep", speed: 180 },
    ],
    bossEnabled: false,
    autoFireRate: 5,
    powerUpDropChance: 0.10,
    skyGradient: ["#87CEEB", "#E0F0FF"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.0,
    terrain: {
      theme: "coastal",
      horizonAssets: ["horizon_coastal"],
      groundColor: "#4d8c3f",
      groundTexture: "ground_grass",
      structurePool: ["struct_beach_hut", "struct_lighthouse", "struct_palm_tree"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_debris"],
      propDensity: 3,
      hasWater: true,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(200, 230, 255, 0.6)",
        count: 30,
        speedRange: [15, 40],
        sizeRange: [1, 2.5],
        drift: 20,
      },
    },
  },
  {
    level: 2,
    name: "Desert Strike",
    waves: [
      { enemyVariant: "scout", count: 5, spawnDelay: 0.7, waveDelay: 1, formation: "line", speed: 170 },
      { enemyVariant: "fighter", count: 3, spawnDelay: 1.0, waveDelay: 7, formation: "v", speed: 120 },
      { enemyVariant: "dart", count: 6, spawnDelay: 0.5, waveDelay: 11, formation: "sweep", speed: 280 },
      { enemyVariant: "scout", count: 6, spawnDelay: 0.6, waveDelay: 14, formation: "sweep", speed: 180 },
      { enemyVariant: "fighter", count: 4, spawnDelay: 0.9, waveDelay: 20, formation: "random", speed: 130, weaponType: "spread" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.4, waveDelay: 25, formation: "line", speed: 300 },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.5, waveDelay: 28, formation: "line", speed: 190 },
    ],
    bossEnabled: false,
    autoFireRate: 5,
    powerUpDropChance: 0.12,
    skyGradient: ["#F4A460", "#87CEEB"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.0,
    weaponDrops: ["missile"] as WeaponType[],
    terrain: {
      theme: "desert",
      horizonAssets: ["horizon_desert"],
      groundColor: "#c8a060",
      groundTexture: "ground_sand",
      structurePool: ["struct_oil_rig", "struct_cactus", "struct_bunker"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_crater", "prop_tire_tracks"],
      propDensity: 4,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(210, 180, 120, 0.5)",
        count: 50,
        speedRange: [20, 60],
        sizeRange: [0.5, 2],
        drift: 40,
      },
    },
  },
  {
    level: 3,
    name: "Mountain Assault",
    waves: [
      { enemyVariant: "scout", count: 6, spawnDelay: 0.6, waveDelay: 1, formation: "v", speed: 180 },
      { enemyVariant: "fighter", count: 4, spawnDelay: 0.8, waveDelay: 7, formation: "line", speed: 140 },
      { enemyVariant: "interceptor", count: 4, spawnDelay: 0.6, waveDelay: 11, formation: "v", speed: 250 },
      { enemyVariant: "bomber", count: 2, spawnDelay: 1.2, waveDelay: 14, formation: "random", speed: 80, weaponType: "spread" },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.5, waveDelay: 19, formation: "sweep", speed: 190 },
      { enemyVariant: "swarmer", count: 6, spawnDelay: 0.5, waveDelay: 22, formation: "random", speed: 170 },
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 25, formation: "v", speed: 150, weaponType: "spread" },
      { enemyVariant: "drone", count: 6, spawnDelay: 0.4, waveDelay: 28, formation: "random", speed: 170 },
      { enemyVariant: "bomber", count: 3, spawnDelay: 1.0, waveDelay: 32, formation: "line", speed: 90, weaponType: "spread" },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 20, speed: 40, fireRate: 1.2, scoreValue: 200, appearsAfterWave: 5, weaponType: "missile" },
    autoFireRate: 6,
    powerUpDropChance: 0.15,
    skyGradient: ["#4A6670", "#8BA8B7"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.2,
    weaponDrops: ["missile", "laser", "auto-gun"] as WeaponType[],
    terrain: {
      theme: "mountain",
      horizonAssets: ["horizon_mountain"],
      groundColor: "#3d5a3d",
      groundTexture: "ground_grass",
      structurePool: ["struct_pine_tree", "struct_watchtower", "struct_radar_dish", "struct_bunker"],
      structureDensity: 3,
      propPool: ["prop_rocks", "prop_debris", "prop_crater"],
      propDensity: 4,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(140, 100, 50, 0.4)",
        count: 25,
        speedRange: [10, 30],
        sizeRange: [1, 3],
        drift: 30,
      },
    },
  },
  {
    level: 4,
    name: "Arctic Thunder",
    waves: [
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 1, formation: "line", speed: 150, weaponType: "missile" },
      { enemyVariant: "bomber", count: 3, spawnDelay: 1.0, waveDelay: 7, formation: "v", speed: 90, weaponType: "spread" },
      { enemyVariant: "gunship", count: 3, spawnDelay: 0.9, waveDelay: 10, formation: "line", speed: 110, weaponType: "spread" },
      { enemyVariant: "scout", count: 8, spawnDelay: 0.4, waveDelay: 13, formation: "sweep", speed: 200 },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.6, waveDelay: 18, formation: "random", speed: 160, weaponType: "missile" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.3, waveDelay: 21, formation: "sweep", speed: 290 },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.9, waveDelay: 24, formation: "line", speed: 100, weaponType: "missile" },
      { enemyVariant: "fighter", count: 5, spawnDelay: 0.7, waveDelay: 31, formation: "v", speed: 150, weaponType: "missile" },
      { enemyVariant: "gunship", count: 4, spawnDelay: 0.8, waveDelay: 34, formation: "v", speed: 120, weaponType: "spread" },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 37, formation: "sweep", speed: 210 },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 30, speed: 35, fireRate: 1.5, scoreValue: 300, appearsAfterWave: 6, weaponType: "laser" },
    autoFireRate: 6,
    powerUpDropChance: 0.15,
    skyGradient: ["#B0C4DE", "#D3D3D3"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.4,
    weaponDrops: ["missile", "laser", "plasma", "auto-gun"] as WeaponType[],
    terrain: {
      theme: "arctic",
      horizonAssets: ["horizon_arctic"],
      groundColor: "#e0e8ee",
      groundTexture: "ground_snow",
      structurePool: ["struct_barracks", "struct_radar_dish", "struct_bunker", "struct_watchtower"],
      structureDensity: 2,
      propPool: ["prop_rocks", "prop_crater", "prop_debris"],
      propDensity: 3,
      hasWater: true,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(240, 245, 255, 0.8)",
        count: 70,
        speedRange: [25, 70],
        sizeRange: [1, 3],
        drift: 25,
      },
    },
  },
  {
    level: 5,
    name: "Final Fortress",
    waves: [
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.6, waveDelay: 1, formation: "v", speed: 160, weaponType: "spread" },
      { enemyVariant: "bomber", count: 3, spawnDelay: 0.9, waveDelay: 6, formation: "line", speed: 100, weaponType: "missile" },
      { enemyVariant: "stealth", count: 3, spawnDelay: 0.8, waveDelay: 9, formation: "random", speed: 160 },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 12, formation: "sweep", speed: 220 },
      { enemyVariant: "interceptor", count: 5, spawnDelay: 0.5, waveDelay: 15, formation: "v", speed: 260 },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.5, waveDelay: 17, formation: "random", speed: 170, weaponType: "missile" },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.8, waveDelay: 22, formation: "v", speed: 110, weaponType: "spread" },
      { enemyVariant: "cruiser", count: 1, spawnDelay: 0, waveDelay: 25, formation: "line", speed: 60, weaponType: "missile" },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 28, formation: "line", speed: 180, weaponType: "laser" },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 34, formation: "random", speed: 110, weaponType: "missile" },
      { enemyVariant: "swarmer", count: 8, spawnDelay: 0.4, waveDelay: 37, formation: "random", speed: 180 },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 40, formation: "sweep", speed: 230 },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 50, speed: 30, fireRate: 2.0, scoreValue: 500, appearsAfterWave: 7, weaponType: "laser" },
    autoFireRate: 7,
    powerUpDropChance: 0.18,
    skyGradient: ["#2F1B14", "#1a1a1a"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.6,
    weaponDrops: ["missile", "laser", "plasma", "auto-gun", "rocket"] as WeaponType[],
    terrain: {
      theme: "fortress",
      horizonAssets: ["horizon_fortress"],
      groundColor: "#3a3a3a",
      groundTexture: "ground_concrete",
      structurePool: [
        "struct_wall_segment", "struct_aa_gun", "struct_hangar",
        "struct_command_center", "struct_bunker",
      ],
      structureDensity: 3,
      propPool: ["prop_crater", "prop_debris", "prop_tire_tracks", "prop_rocks"],
      propDensity: 5,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(255, 140, 50, 0.5)",
        count: 40,
        speedRange: [15, 50],
        sizeRange: [0.5, 2],
        drift: 15,
      },
    },
  },
  {
    level: 6,
    name: "Shipyard Ruins",
    waves: [
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.6, waveDelay: 1, formation: "line", speed: 170, weaponType: "spread" },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.8, waveDelay: 6, formation: "v", speed: 110, weaponType: "missile" },
      { enemyVariant: "destroyer", count: 1, spawnDelay: 0, waveDelay: 9, formation: "line", speed: 50, weaponType: "laser" },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 12, formation: "sweep", speed: 220 },
      { enemyVariant: "fighter", count: 7, spawnDelay: 0.5, waveDelay: 17, formation: "random", speed: 180, weaponType: "missile" },
      { enemyVariant: "stealth", count: 4, spawnDelay: 0.7, waveDelay: 20, formation: "random", speed: 170 },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 23, formation: "line", speed: 110, weaponType: "missile" },
      { enemyVariant: "minelayer", count: 2, spawnDelay: 3.0, waveDelay: 26, formation: "sweep", speed: 100 },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 29, formation: "v", speed: 190, weaponType: "missile" },
      { enemyVariant: "fighter", count: 9, spawnDelay: 0.4, waveDelay: 35, formation: "sweep", speed: 190, weaponType: "spread" },
      { enemyVariant: "gunship", count: 4, spawnDelay: 0.7, waveDelay: 38, formation: "v", speed: 120, weaponType: "spread" },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 41, formation: "sweep", speed: 230 },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 47, formation: "random", speed: 120, weaponType: "missile" },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 40, speed: 30, fireRate: 1.8, scoreValue: 400, appearsAfterWave: 7, weaponType: "laser" },
    autoFireRate: 7,
    powerUpDropChance: 0.18,
    skyGradient: ["#2b1d1d", "#4a3333"],
    starDensity: 0,
    enemyFireRateMultiplier: 1.8,
    weaponDrops: ["missile", "laser", "plasma", "ion-cannon", "rocket"] as WeaponType[],
    terrain: {
      theme: "shipyard",
      horizonAssets: ["horizon_shipyard"],
      groundColor: "#3a2f2a",
      groundTexture: "ground_rust",
      structurePool: ["struct_crane", "struct_drydock", "struct_ship_hull", "struct_cargo_container"],
      structureDensity: 3,
      propPool: ["prop_scrap_metal", "prop_oil_drum", "prop_debris", "prop_anchor"],
      propDensity: 5,
      hasWater: true,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(180, 120, 60, 0.5)",
        count: 35,
        speedRange: [10, 35],
        sizeRange: [0.5, 2],
        drift: 15,
      },
      hazeColor: "rgba(60, 40, 30, 1)",
      hazeOpacity: 0.12,
      secondaryParticles: {
        color: "rgba(160, 150, 140, 0.5)",
        count: 30,
        speedRange: [15, 40],
        sizeRange: [1, 3],
        drift: 20,
      },
      litStructures: ["struct_crane", "struct_drydock"],
    },
  },
  {
    level: 7,
    name: "Scorched Wastes",
    waves: [
      { enemyVariant: "fighter", count: 7, spawnDelay: 0.5, waveDelay: 1, formation: "v", speed: 180, weaponType: "missile" },
      { enemyVariant: "bomber", count: 4, spawnDelay: 0.8, waveDelay: 6, formation: "line", speed: 110, weaponType: "spread" },
      { enemyVariant: "gunship", count: 4, spawnDelay: 0.7, waveDelay: 8, formation: "line", speed: 120, weaponType: "spread" },
      { enemyVariant: "scout", count: 10, spawnDelay: 0.3, waveDelay: 11, formation: "sweep", speed: 230 },
      { enemyVariant: "drone", count: 8, spawnDelay: 0.3, waveDelay: 14, formation: "random", speed: 180 },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 16, formation: "random", speed: 190, weaponType: "missile" },
      { enemyVariant: "bomber", count: 3, spawnDelay: 0.9, waveDelay: 16, formation: "line", speed: 110, weaponType: "missile" },
      { enemyVariant: "cruiser", count: 2, spawnDelay: 2.0, waveDelay: 20, formation: "line", speed: 65, weaponType: "missile" },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 23, formation: "v", speed: 120, weaponType: "missile" },
      { enemyVariant: "interceptor", count: 6, spawnDelay: 0.4, waveDelay: 26, formation: "v", speed: 260 },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 29, formation: "line", speed: 240 },
      { enemyVariant: "swarmer", count: 6, spawnDelay: 0.4, waveDelay: 31, formation: "random", speed: 180 },
      { enemyVariant: "fighter", count: 6, spawnDelay: 0.5, waveDelay: 34, formation: "sweep", speed: 180, weaponType: "missile" },
      { enemyVariant: "minelayer", count: 1, spawnDelay: 0, waveDelay: 37, formation: "sweep", speed: 100 },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 40, formation: "random", speed: 120, weaponType: "spread" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.3, waveDelay: 43, formation: "sweep", speed: 290 },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 46, formation: "sweep", speed: 240 },
      { enemyVariant: "destroyer", count: 1, spawnDelay: 0, waveDelay: 49, formation: "line", speed: 50, weaponType: "laser" },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 55, speed: 29, fireRate: 2.0, scoreValue: 500, appearsAfterWave: 8, weaponType: "laser" },
    autoFireRate: 8,
    powerUpDropChance: 0.19,
    skyGradient: ["#1a1a0e", "#3d3520"],
    starDensity: 0,
    enemyFireRateMultiplier: 2.0,
    weaponDrops: ["missile", "laser", "plasma", "ion-cannon", "rocket"] as WeaponType[],
    terrain: {
      theme: "wasteland",
      horizonAssets: ["horizon_wasteland"],
      groundColor: "#2e2a1e",
      groundTexture: "ground_ash",
      structurePool: ["struct_ruin", "struct_dead_tree", "struct_wrecked_tank", "struct_bunker"],
      structureDensity: 2,
      propPool: ["prop_crater", "prop_bones", "prop_radiation_sign", "prop_debris"],
      propDensity: 5,
      hasWater: false,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(100, 90, 60, 0.6)",
        count: 60,
        speedRange: [15, 50],
        sizeRange: [0.5, 3],
        drift: 35,
      },
      hazeColor: "rgba(80, 60, 20, 1)",
      hazeOpacity: 0.15,
      secondaryParticles: {
        color: "rgba(255, 140, 40, 0.7)",
        count: 40,
        speedRange: [-40, -15],
        sizeRange: [1, 2.5],
        drift: 10,
      },
      litStructures: ["struct_ruin", "struct_wrecked_tank"],
    },
  },
  {
    level: 8,
    name: "Industrial Core",
    waves: [
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.5, waveDelay: 1, formation: "line", speed: 190, weaponType: "missile" },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 6, formation: "v", speed: 120, weaponType: "missile" },
      { enemyVariant: "destroyer", count: 2, spawnDelay: 3.0, waveDelay: 9, formation: "line", speed: 50, weaponType: "laser" },
      { enemyVariant: "scout", count: 12, spawnDelay: 0.25, waveDelay: 11, formation: "sweep", speed: 240 },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 16, formation: "random", speed: 200, weaponType: "laser" },
      { enemyVariant: "stealth", count: 4, spawnDelay: 0.6, waveDelay: 19, formation: "random", speed: 180 },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 21, formation: "line", speed: 130, weaponType: "missile" },
      { enemyVariant: "minelayer", count: 1, spawnDelay: 0, waveDelay: 24, formation: "sweep", speed: 100 },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.35, waveDelay: 27, formation: "v", speed: 200, weaponType: "missile" },
      { enemyVariant: "cruiser", count: 2, spawnDelay: 2.0, waveDelay: 30, formation: "line", speed: 65, weaponType: "missile" },
      { enemyVariant: "bomber", count: 5, spawnDelay: 0.7, waveDelay: 33, formation: "random", speed: 120, weaponType: "missile" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.3, waveDelay: 36, formation: "sweep", speed: 290 },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 39, formation: "sweep", speed: 250 },
      { enemyVariant: "gunship", count: 5, spawnDelay: 0.6, waveDelay: 42, formation: "v", speed: 130, weaponType: "spread" },
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 45, formation: "line", speed: 200, weaponType: "laser" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 48, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "bomber", count: 7, spawnDelay: 0.5, waveDelay: 51, formation: "v", speed: 130, weaponType: "missile" },
      { enemyVariant: "swarmer", count: 6, spawnDelay: 0.4, waveDelay: 54, formation: "random", speed: 180 },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 65, speed: 28, fireRate: 2.2, scoreValue: 600, appearsAfterWave: 8, weaponType: "laser" },
    autoFireRate: 8,
    powerUpDropChance: 0.19,
    skyGradient: ["#1c1c1c", "#333030"],
    starDensity: 0,
    enemyFireRateMultiplier: 2.2,
    weaponDrops: ["missile", "laser", "plasma", "ion-cannon", "rocket"] as WeaponType[],
    terrain: {
      theme: "industrial",
      horizonAssets: ["horizon_industrial"],
      groundColor: "#2a2a2a",
      groundTexture: "ground_metal",
      structurePool: ["struct_smokestack", "struct_factory", "struct_conveyor", "struct_cooling_tower", "struct_pipe_cluster"],
      structureDensity: 4,
      propPool: ["prop_oil_drum", "prop_debris", "prop_grate", "prop_steam_vent"],
      propDensity: 6,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(80, 80, 80, 0.7)",
        count: 55,
        speedRange: [20, 60],
        sizeRange: [1, 3],
        drift: 10,
      },
      hazeColor: "rgba(50, 50, 50, 1)",
      hazeOpacity: 0.18,
      secondaryParticles: {
        color: "rgba(255, 100, 20, 0.7)",
        count: 50,
        speedRange: [-40, -15],
        sizeRange: [0.5, 2],
        drift: 8,
      },
      scanlines: true,
      litStructures: ["struct_smokestack", "struct_factory", "struct_cooling_tower"],
    },
  },
  {
    level: 9,
    name: "Orbital Debris",
    waves: [
      { enemyVariant: "fighter", count: 8, spawnDelay: 0.4, waveDelay: 1, formation: "v", speed: 200, weaponType: "laser" },
      { enemyVariant: "interceptor", count: 6, spawnDelay: 0.4, waveDelay: 4, formation: "v", speed: 270 },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 6, formation: "line", speed: 130, weaponType: "missile" },
      { enemyVariant: "drone", count: 10, spawnDelay: 0.25, waveDelay: 9, formation: "random", speed: 190 },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 11, formation: "sweep", speed: 250 },
      { enemyVariant: "swarmer", count: 8, spawnDelay: 0.35, waveDelay: 14, formation: "random", speed: 190 },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.35, waveDelay: 16, formation: "random", speed: 200, weaponType: "missile" },
      { enemyVariant: "destroyer", count: 2, spawnDelay: 3.0, waveDelay: 19, formation: "line", speed: 55, weaponType: "laser" },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 21, formation: "v", speed: 130, weaponType: "laser" },
      { enemyVariant: "dart", count: 8, spawnDelay: 0.3, waveDelay: 24, formation: "sweep", speed: 290 },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 27, formation: "line", speed: 250 },
      { enemyVariant: "cruiser", count: 2, spawnDelay: 2.0, waveDelay: 30, formation: "line", speed: 65, weaponType: "missile" },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.35, waveDelay: 33, formation: "sweep", speed: 200, weaponType: "missile" },
      { enemyVariant: "stealth", count: 5, spawnDelay: 0.5, waveDelay: 36, formation: "random", speed: 180 },
      { enemyVariant: "bomber", count: 7, spawnDelay: 0.5, waveDelay: 39, formation: "random", speed: 130, weaponType: "missile" },
      { enemyVariant: "minelayer", count: 1, spawnDelay: 0, waveDelay: 42, formation: "sweep", speed: 100 },
      { enemyVariant: "scout", count: 16, spawnDelay: 0.18, waveDelay: 45, formation: "sweep", speed: 250 },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.3, waveDelay: 51, formation: "v", speed: 200, weaponType: "laser" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 54, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "bomber", count: 8, spawnDelay: 0.4, waveDelay: 57, formation: "line", speed: 130, weaponType: "laser" },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 75, speed: 27, fireRate: 2.3, scoreValue: 750, appearsAfterWave: 9, weaponType: "laser" },
    autoFireRate: 9,
    powerUpDropChance: 0.19,
    skyGradient: ["#050510", "#0a0a20"],
    starDensity: 40,
    enemyFireRateMultiplier: 2.4,
    weaponDrops: ["missile", "laser", "plasma", "ion-cannon", "rocket"] as WeaponType[],
    terrain: {
      theme: "orbital",
      horizonAssets: ["horizon_orbital"],
      groundColor: "#0c0c14",
      groundTexture: "ground_hull_plate",
      structurePool: ["struct_satellite_dish", "struct_solar_panel", "struct_station_module", "struct_antenna_array"],
      structureDensity: 3,
      propPool: ["prop_space_debris", "prop_hull_fragment", "prop_wiring", "prop_panel_shard"],
      propDensity: 6,
      hasWater: false,
      hasRoads: false,
      ambientParticles: {
        color: "rgba(150, 180, 255, 0.4)",
        count: 30,
        speedRange: [5, 20],
        sizeRange: [0.5, 1.5],
        drift: 5,
      },
      hazeColor: "rgba(10, 10, 30, 1)",
      hazeOpacity: 0.08,
      secondaryParticles: {
        color: "rgba(180, 200, 255, 0.6)",
        count: 25,
        speedRange: [-10, 10],
        sizeRange: [0.5, 1.5],
        drift: 15,
      },
      scanlines: true,
      litStructures: ["struct_station_module", "struct_antenna_array"],
    },
  },
  {
    level: 10,
    name: "Cylon Stronghold",
    waves: [
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.35, waveDelay: 1, formation: "line", speed: 200, weaponType: "laser" },
      { enemyVariant: "dart", count: 10, spawnDelay: 0.25, waveDelay: 4, formation: "sweep", speed: 300 },
      { enemyVariant: "bomber", count: 6, spawnDelay: 0.6, waveDelay: 6, formation: "v", speed: 130, weaponType: "missile" },
      { enemyVariant: "gunship", count: 5, spawnDelay: 0.6, waveDelay: 9, formation: "line", speed: 130, weaponType: "spread" },
      { enemyVariant: "scout", count: 14, spawnDelay: 0.2, waveDelay: 11, formation: "sweep", speed: 250 },
      { enemyVariant: "cruiser", count: 2, spawnDelay: 2.0, waveDelay: 14, formation: "line", speed: 65, weaponType: "missile" },
      { enemyVariant: "fighter", count: 10, spawnDelay: 0.3, waveDelay: 16, formation: "random", speed: 200, weaponType: "missile" },
      { enemyVariant: "bomber", count: 7, spawnDelay: 0.5, waveDelay: 21, formation: "line", speed: 130, weaponType: "laser" },
      { enemyVariant: "destroyer", count: 2, spawnDelay: 3.0, waveDelay: 24, formation: "line", speed: 55, weaponType: "laser" },
      { enemyVariant: "fighter", count: 12, spawnDelay: 0.3, waveDelay: 27, formation: "v", speed: 200, weaponType: "laser" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 30, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "scout", count: 16, spawnDelay: 0.18, waveDelay: 33, formation: "sweep", speed: 250 },
      { enemyVariant: "minelayer", count: 2, spawnDelay: 3.0, waveDelay: 36, formation: "sweep", speed: 110 },
      { enemyVariant: "bomber", count: 8, spawnDelay: 0.5, waveDelay: 39, formation: "random", speed: 130, weaponType: "missile" },
      { enemyVariant: "fighter", count: 12, spawnDelay: 0.25, waveDelay: 45, formation: "line", speed: 200, weaponType: "missile" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 48, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "scout", count: 18, spawnDelay: 0.15, waveDelay: 51, formation: "sweep", speed: 250 },
      { enemyVariant: "bomber", count: 8, spawnDelay: 0.4, waveDelay: 57, formation: "v", speed: 130, weaponType: "laser" },
      { enemyVariant: "juggernaut", count: 1, spawnDelay: 0, waveDelay: 60, formation: "line", speed: 35, weaponType: "missile" },
      { enemyVariant: "fighter", count: 14, spawnDelay: 0.2, waveDelay: 63, formation: "line", speed: 200, weaponType: "laser" },
    ],
    bossEnabled: true,
    bossConfig: { hitPoints: 100, speed: 25, fireRate: 2.5, scoreValue: 1000, appearsAfterWave: 10, weaponType: "laser" },
    autoFireRate: 9,
    powerUpDropChance: 0.20,
    skyGradient: ["#0a0000", "#1a0505"],
    starDensity: 50,
    enemyFireRateMultiplier: 2.5,
    weaponDrops: ["missile", "laser", "plasma", "ion-cannon", "rocket"] as WeaponType[],
    terrain: {
      theme: "stronghold",
      horizonAssets: ["horizon_stronghold"],
      groundColor: "#1a1a1a",
      groundTexture: "ground_dark_metal",
      structurePool: ["struct_cylon_tower", "struct_turret_base", "struct_heavy_gate", "struct_reactor_core", "struct_aa_gun"],
      structureDensity: 4,
      propPool: ["prop_red_light", "prop_debris", "prop_cable_cluster", "prop_vent_grate", "prop_blast_mark"],
      propDensity: 7,
      hasWater: false,
      hasRoads: true,
      ambientParticles: {
        color: "rgba(255, 40, 40, 0.4)",
        count: 45,
        speedRange: [10, 40],
        sizeRange: [0.5, 2],
        drift: 8,
      },
      hazeColor: "rgba(40, 5, 5, 1)",
      hazeOpacity: 0.20,
      secondaryParticles: {
        color: "rgba(255, 60, 20, 0.7)",
        count: 60,
        speedRange: [-40, -15],
        sizeRange: [0.5, 2],
        drift: 10,
      },
      scanlines: true,
      litStructures: ["struct_cylon_tower", "struct_reactor_core", "struct_turret_base"],
    },
  },
];
