export interface AudioAssetManifest {
  sfx: Record<string, string>;
  music: Record<string, string>;
}

export const AUDIO_MANIFEST: AudioAssetManifest = {
  sfx: {
    player_shoot:     "assets/raptor/audio/sfx/player_shoot.mp3",
    enemy_shoot:      "assets/raptor/audio/sfx/enemy_shoot.mp3",
    enemy_hit:        "assets/raptor/audio/sfx/enemy_hit.mp3",
    enemy_destroy:    "assets/raptor/audio/sfx/enemy_destroy.mp3",
    player_hit:       "assets/raptor/audio/sfx/player_hit.mp3",
    player_destroy:   "assets/raptor/audio/sfx/player_destroy.mp3",
    boss_hit:         "assets/raptor/audio/sfx/boss_hit.mp3",
    boss_destroy:     "assets/raptor/audio/sfx/boss_destroy.mp3",
    power_up_collect: "assets/raptor/audio/sfx/power_up_collect.mp3",
    level_complete:   "assets/raptor/audio/sfx/level_complete.mp3",
    game_over:        "assets/raptor/audio/sfx/game_over.mp3",
    victory:          "assets/raptor/audio/sfx/victory.mp3",
    menu_start:       "assets/raptor/audio/sfx/menu_start.mp3",
    missile_fire:     "assets/raptor/audio/sfx/missile_fire.mp3",
    missile_hit:      "assets/raptor/audio/sfx/missile_hit.mp3",
    laser_fire:       "assets/raptor/audio/sfx/laser_fire.mp3",
    laser_hit:        "assets/raptor/audio/sfx/laser_hit.mp3",
    weapon_switch:    "assets/raptor/audio/sfx/weapon_switch.mp3",
    weapon_upgrade:   "assets/raptor/audio/sfx/weapon_upgrade.mp3",
    enemy_missile_fire: "assets/raptor/audio/sfx/enemy_missile_fire.mp3",
    enemy_missile_hit:  "assets/raptor/audio/sfx/enemy_missile_hit.mp3",
    enemy_spread_fire:  "assets/raptor/audio/sfx/enemy_spread_fire.mp3",
    enemy_laser_fire:   "assets/raptor/audio/sfx/enemy_laser_fire.mp3",
    enemy_laser_hit:    "assets/raptor/audio/sfx/enemy_laser_hit.mp3",
    plasma_fire:        "assets/raptor/audio/sfx/plasma_fire.mp3",
    plasma_hit:         "assets/raptor/audio/sfx/plasma_hit.mp3",
    ion_fire:           "assets/raptor/audio/sfx/ion_fire.mp3",
    ion_hit:            "assets/raptor/audio/sfx/ion_hit.mp3",
    rocket_fire:        "assets/raptor/audio/sfx/rocket_fire.mp3",
    turret_fire:        "assets/raptor/audio/sfx/player_shoot.mp3",
    mega_bomb_fire:     "assets/raptor/audio/sfx/mega_bomb_fire.mp3",
    emp_burst:          "assets/raptor/audio/sfx/emp_burst.mp3",
    deflect:            "assets/raptor/audio/sfx/deflect.mp3",
  },
  music: {
    menu:    "assets/raptor/audio/music/menu.mp3",
    level_1: "assets/raptor/audio/music/level_1_coastal.mp3",
    level_2: "assets/raptor/audio/music/level_2_desert.mp3",
    level_3: "assets/raptor/audio/music/level_3_mountain.mp3",
    level_4: "assets/raptor/audio/music/level_4_arctic.mp3",
    level_5:  "assets/raptor/audio/music/level_5_fortress.mp3",
    level_6:  "assets/raptor/audio/music/level_6_shipyard.mp3",
    level_7:  "assets/raptor/audio/music/level_7_wasteland.mp3",
    level_8:  "assets/raptor/audio/music/level_8_industrial.mp3",
    level_9:  "assets/raptor/audio/music/level_9_orbital.mp3",
    level_10: "assets/raptor/audio/music/level_10_stronghold.mp3",
    level_11: "assets/raptor/audio/music/level_11_colony.mp3",
    level_12: "assets/raptor/audio/music/level_12_asteroid.mp3",
    level_13: "assets/raptor/audio/music/level_13_nebula.mp3",
    level_14: "assets/raptor/audio/music/level_14_jungle.mp3",
    level_15: "assets/raptor/audio/music/level_15_volcano.mp3",
    level_16: "assets/raptor/audio/music/level_16_ocean.mp3",
    level_17: "assets/raptor/audio/music/level_17_tundra.mp3",
    level_18: "assets/raptor/audio/music/level_18_ruins.mp3",
    level_19: "assets/raptor/audio/music/level_19_megacity.mp3",
    level_20: "assets/raptor/audio/music/level_20_dominion_base.mp3",
  },
};
